<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>async函數</title>
  </head>
  <body>
    <script>
      // then方法回調的返回結果是和async函數的返回結果規則是一模一樣的
      async function main() {
        // Promise的狀態是由 function函數內部的return所決定的 - 也就是由內部的返回值決定
        // 1. 如果返回值是一個非Promise類型的數據【例如：字符串，布爾值，null，undefined等等】 - 結果值就是一個成功的Promise對象
        // 而且 return後面所寫的是什麼，它成功的結果值就是什麼
        // return 521;
        // 2. 如果返回的是一個 Promise對象
        // return new Promise((resolve, reject) => {
        //   // resolve("OK");
        //   reject("ERROR");
        // });
        throw "OH NO"; // 拋出異常，所返回的結果result，它的狀態就是一個失敗的 promise對象，而且拋出的結果就是result失敗的Promise對象
      }

      let result = main();

      console.log(result);
    </script>
  </body>
</html>
